language: python

python:
- "3.9"

env:
- DJANGO=4.1.2 COVERALLS_REPO_TOKEN=E3p82QfWMQiyUragCsvp731cSSQX88Q9Z

install:
- pip install -r requirements.txt
- pip install black
- python3.9 -m pip install flake8
- pip install pyyaml
- pip install coverage
- pip install coveralls

script:
- export DJANGO_SECRETKEY=secret # needed because settings.py pulls it from os.environ
- black .
- flake8 --max-line-length=100 .
- cd Interactive_Map && coverage run manage.py test map
- cd .. & coveralls

