language: python

python:
- "3.9"

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

env:
- DJANGO=4.1.2

install:
- pip install -r requirements.txt

before_script:
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"

script:
- export DJANGO_SECRETKEY=secret # needed because settings.py pulls it from os.environ
- python manage.py loaddata
- black .
- flake8 --max-line-length=200 .
- coverage run manage.py test map
- coveralls

