language: python

python:
- "3.9"

env:
- DJANGO=4.1.2

install:
- pip install -r requirements.txt
- pip install black
- python3.9 -m pip install flake8
- pip install coverage

script:
- export DJANGO_SECRETKEY=secret # needed because settings.py pulls it from os.environ
- black .
- flake8 --max-line-length=100 .
- coverage run

