language: python

python:
- "3.9"

env:
- DJANGO=4.1.2

install:
- pip install -r requirements.txt

script:
- export DJANGO_SECRETKEY=secret # needed because settings.py pulls it from os.environ
- python manage.py loaddata
- black .
- flake8 --max-line-length=110 .
- coverage run manage.py test map
- coveralls

