language: python

python:
- "3.9"

addons:
  chrome: stable

env:
- DJANGO=4.1.2

install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - sudo apt install chromium-chromedriver
  - cp /usr/lib/chromium-browser/chromedriver /usr/bin
  - pip install -r requirements.txt



script:
- export DJANGO_SECRETKEY=secret # needed because settings.py pulls it from os.environ
- python manage.py loaddata
- black .
- flake8 --max-line-length=200 .
- coverage run manage.py test map
- coveralls
- whereis google-chrome-stable
- whereis chromedriver

