# Generated by Django 4.1.1 on 2022-12-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_firehouseaddresses'),
    ]

    operations = [
    ]
